name: Deploy to Xserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: FTP Deploy
        run: |
          lftp -c "
          set ftp:ssl-allow yes;
          set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }};
          mirror -R --delete --verbose ./public/ company.ringclass.net/public_html/;
          bye;
          "
